title: Chloé Mimeau
description: Maître de conférences (assistant professor) at CNAM Paris
github:
  teaching: https://cmimeau.github.io/webpage/teaching.html
  research: https://cmimeau.github.io/webpage/research.html
  publi: https://cmimeau.github.io/webpage/publications.html
gems:
  - jekyll-seo-tag
google_analytics: true
theme: jekyll-theme-dinky
