title: Chloé Mimeau
description: Maître de conférences. Laboratoire M2N, Conservatoire National des Arts et Métiers Paris
github:
  teaching: https://cmimeau.github.io/webpage/teaching.html
theme: jekyll-theme-dinky
