title: Chloé Mimeau
description: Maître de conférences
github:
  teaching: https://cmimeau.github.io/webpage/teaching.html
  research: https://cmimeau.github.io/webpage/research.html
  publi: https://cmimeau.github.io/webpage/publications.html
plugins:
  - jekyll-seo-tag
theme: jekyll-theme-dinky
